//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointments()
        {
            this.AdapterAppointments = new HashSet<AdapterAppointments>();
            this.OldAdapterAppointments = new HashSet<OldAdapterAppointments>();
        }
    
        public int Id { get; set; }
        public System.Guid InternalId { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Category { get; set; }
        public string Location { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int ReminderMinutesBeforeStart { get; set; }
        public bool Notification { get; set; }
        public bool IsPrivate { get; set; }
        public byte Priority { get; set; }
        public int ConsumerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdapterAppointments> AdapterAppointments { get; set; }
        public virtual Consumers Consumers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OldAdapterAppointments> OldAdapterAppointments { get; set; }
    }
}
