//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeContacts
    {
        public int Id { get; set; }
        public System.Guid InternalId { get; set; }
        public string ExternalId { get; set; }
        public System.DateTime LastModifiedTime { get; set; }
        public string JobTitle { get; set; }
        public string CompanyName { get; set; }
        public string EmailAddress1 { get; set; }
        public string EmailAddress2 { get; set; }
        public string EmailAddress3 { get; set; }
        public string GivenName { get; set; }
        public string MiddleName { get; set; }
        public string Surname { get; set; }
        public string Alias { get; set; }
        public string NickName { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string BusinessPhone { get; set; }
        public string PrimaryPhone { get; set; }
        public string OtherTelephone { get; set; }
        public string HomeAddressCity { get; set; }
        public string HomeAddressCountryOrRegion { get; set; }
        public string HomeAddressPostalCode { get; set; }
        public string HomeAddressState { get; set; }
        public string HomeAddressStreet { get; set; }
        public string OtherAddressCity { get; set; }
        public string OtherAddressPostalCode { get; set; }
        public string OtherAddressCountryOrRegion { get; set; }
        public string OtherAddressState { get; set; }
        public string OtherAddressStreet { get; set; }
        public string BusinessAddressCity { get; set; }
        public string BusinessAddressCountryOrRegion { get; set; }
        public string BusinessAddressState { get; set; }
        public string BusinessAddressStreet { get; set; }
        public string BusinessAddressPostalCode { get; set; }
        public string CategoriesJSON { get; set; }
        public int ServiceAccountId { get; set; }
        public bool Upload { get; set; }
        public Nullable<int> Tag { get; set; }
        public bool IsNew { get; set; }
        public bool WasJustUpdated { get; set; }
        public int DownloadRound { get; set; }
        public string LastDLError { get; set; }
        public string LastUPError { get; set; }
    
        public virtual ServiceAccounts ServiceAccounts { get; set; }
    }
}
