//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeAppointments
    {
        public int Id { get; set; }
        public System.Guid InternalId { get; set; }
        public string ExternalId { get; set; }
        public string Body { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public System.DateTime LastModifiedTime { get; set; }
        public string Location { get; set; }
        public bool IsReminderSet { get; set; }
        public byte AppointmentState { get; set; }
        public string Subject { get; set; }
        public string RequiredAttendeesJSON { get; set; }
        public int ReminderMinutesBeforeStart { get; set; }
        public byte Sensitivity { get; set; }
        public string RecurrenceJSON { get; set; }
        public string ModifiedOccurrencesJSON { get; set; }
        public string LastOccurrenceJSON { get; set; }
        public bool IsRecurring { get; set; }
        public bool IsCancelled { get; set; }
        public string ICalRecurrenceId { get; set; }
        public string FirstOccurrenceJSON { get; set; }
        public string DeletedOccurrencesJSON { get; set; }
        public byte AppointmentType { get; set; }
        public int Duration { get; set; }
        public string StartTimeZone { get; set; }
        public string EndTimeZone { get; set; }
        public bool AllowNewTimeProposal { get; set; }
        public string CategoriesJSON { get; set; }
        public int ServiceAccountId { get; set; }
        public bool Upload { get; set; }
        public Nullable<int> Tag { get; set; }
        public bool IsNew { get; set; }
        public bool WasJustUpdated { get; set; }
        public int DownloadRound { get; set; }
        public string LastDLError { get; set; }
        public string LastUPError { get; set; }
    
        public virtual ServiceAccounts ServiceAccounts { get; set; }
    }
}
