//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleContacts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoogleContacts()
        {
            this.GoogleAddresses = new HashSet<GoogleAddresses>();
            this.GoogleEmails = new HashSet<GoogleEmails>();
            this.GoogleGroupMemberships = new HashSet<GoogleGroupMemberships>();
            this.GooglePhoneNumbers = new HashSet<GooglePhoneNumbers>();
        }
    
        public int Id { get; set; }
        public System.Guid InternalId { get; set; }
        public string ExternalId { get; set; }
        public System.DateTime ChangedOn { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string GivenName { get; set; }
        public string FamilyName { get; set; }
        public string OrgDepartment { get; set; }
        public string OrgJobDescription { get; set; }
        public string OrgName { get; set; }
        public string OrgTitle { get; set; }
        public string PrimaryPhonenumber { get; set; }
        public string postalAddressCity { get; set; }
        public string postalAddressStreet { get; set; }
        public string postalAddressRegion { get; set; }
        public string postalAddressPostcode { get; set; }
        public string postalAddressCountry { get; set; }
        public string postalAddressFormattedAddress { get; set; }
        public bool Upload { get; set; }
        public Nullable<int> Tag { get; set; }
        public bool IsNew { get; set; }
        public bool WasJustUpdated { get; set; }
        public string LastDLError { get; set; }
        public string LastUPError { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoogleAddresses> GoogleAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoogleEmails> GoogleEmails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoogleGroupMemberships> GoogleGroupMemberships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GooglePhoneNumbers> GooglePhoneNumbers { get; set; }
    }
}
