//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleEmails
    {
        public int Id { get; set; }
        public System.Guid InternalId { get; set; }
        public string ExternalId { get; set; }
        public string Address { get; set; }
        public string Label { get; set; }
        public Nullable<bool> Home { get; set; }
        public Nullable<bool> Other { get; set; }
        public Nullable<bool> Work { get; set; }
        public int ContactId { get; set; }
    
        public virtual GoogleContacts GoogleContacts { get; set; }
    }
}
