//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processes
    {
        public int Id { get; set; }
        public System.DateTime StartedOn { get; set; }
        public Nullable<System.DateTime> FinishedOn { get; set; }
        public string Name { get; set; }
        public string XamlCode { get; set; }
        public string Exception { get; set; }
        public int WorkflowId { get; set; }
    
        public virtual Workflows Workflows { get; set; }
    }
}
