//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceAccounts()
        {
            this.CalDavEvents = new HashSet<CalDavEvents>();
            this.ExchangeAppointments = new HashSet<ExchangeAppointments>();
            this.ExchangeContacts = new HashSet<ExchangeContacts>();
            this.ExchangeEmailMessages = new HashSet<ExchangeEmailMessages>();
        }
    
        public int Id { get; set; }
        public string LoginJSON { get; set; }
        public int ServiceId { get; set; }
        public int AccountId { get; set; }
        public Nullable<System.DateTime> LastSuccessfulDownload { get; set; }
        public Nullable<System.DateTime> LastDownloadAttempt { get; set; }
        public Nullable<System.DateTime> LastSuccessfulUpload { get; set; }
        public Nullable<System.DateTime> LastUploadAttempt { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalDavEvents> CalDavEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExchangeAppointments> ExchangeAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExchangeContacts> ExchangeContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExchangeEmailMessages> ExchangeEmailMessages { get; set; }
        public virtual Services Services { get; set; }
    }
}
