//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<AdapterAppointments> AdapterAppointments { get; set; }
        public virtual DbSet<Adapters> Adapters { get; set; }
        public virtual DbSet<AppointmentLevels> AppointmentLevels { get; set; }
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<CalDavEvents> CalDavEvents { get; set; }
        public virtual DbSet<ConsumerAdapters> ConsumerAdapters { get; set; }
        public virtual DbSet<Consumers> Consumers { get; set; }
        public virtual DbSet<CustomerCategories> CustomerCategories { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<ExchangeAppointments> ExchangeAppointments { get; set; }
        public virtual DbSet<ExchangeContacts> ExchangeContacts { get; set; }
        public virtual DbSet<ExchangeEmailMessages> ExchangeEmailMessages { get; set; }
        public virtual DbSet<FloresActivities> FloresActivities { get; set; }
        public virtual DbSet<FloresFirms> FloresFirms { get; set; }
        public virtual DbSet<FloresPersons> FloresPersons { get; set; }
        public virtual DbSet<GoogleAddresses> GoogleAddresses { get; set; }
        public virtual DbSet<GoogleContacts> GoogleContacts { get; set; }
        public virtual DbSet<GoogleEmails> GoogleEmails { get; set; }
        public virtual DbSet<GoogleGroupMemberships> GoogleGroupMemberships { get; set; }
        public virtual DbSet<GoogleGroups> GoogleGroups { get; set; }
        public virtual DbSet<GooglePhoneNumbers> GooglePhoneNumbers { get; set; }
        public virtual DbSet<Journals> Journals { get; set; }
        public virtual DbSet<OldAdapterAppointments> OldAdapterAppointments { get; set; }
        public virtual DbSet<Processes> Processes { get; set; }
        public virtual DbSet<ProductCategories> ProductCategories { get; set; }
        public virtual DbSet<ProductCategoryMemberships> ProductCategoryMemberships { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductSoldToCustomers> ProductSoldToCustomers { get; set; }
        public virtual DbSet<ProductUsages> ProductUsages { get; set; }
        public virtual DbSet<ServiceAccounts> ServiceAccounts { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Workflows> Workflows { get; set; }
    }
}
