//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerAdapters
    {
        public int Id { get; set; }
        public int AdapterId { get; set; }
        public int ConsumerId { get; set; }
        public string DateJSON { get; set; }
    
        public virtual Adapters Adapters { get; set; }
        public virtual Consumers Consumers { get; set; }
    }
}
