//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FloresActivities
    {
        public int Id { get; set; }
        public System.Guid InternalId { get; set; }
        public string ExternalId { get; set; }
        public System.DateTime RealEndDate { get; set; }
        public System.DateTime CorrectedDATE { get; set; }
        public string Description { get; set; }
        public System.DateTime SheduledStartDate { get; set; }
        public string Subject { get; set; }
        public System.DateTime RealStartDate { get; set; }
        public string ActivityType_ID { get; set; }
        public System.DateTime SheduledEndDate { get; set; }
        public string ResponsibleUser_ID { get; set; }
        public string Period_ID { get; set; }
        public string Status_ID { get; set; }
        public string Division_ID { get; set; }
        public string Firm_ID { get; set; }
        public string Person_ID { get; set; }
        public string OutlookCategory_ID { get; set; }
        public string FirmOffice_Address { get; set; }
        public string Firm_Address { get; set; }
        public bool Upload { get; set; }
        public Nullable<int> Tag { get; set; }
        public bool IsNew { get; set; }
        public bool WasJustUpdated { get; set; }
        public string LastDLError { get; set; }
        public string LastUPError { get; set; }
    }
}
