//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleGroupMemberships
    {
        public int Id { get; set; }
        public System.Guid InternalId { get; set; }
        public string ExternalId { get; set; }
        public System.DateTime ChangedOn { get; set; }
        public int ContactId { get; set; }
        public int GroupId { get; set; }
    
        public virtual GoogleContacts GoogleContacts { get; set; }
        public virtual GoogleGroups GoogleGroups { get; set; }
    }
}
