//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldAdapterAppointments
    {
        public int Id { get; set; }
        public System.Guid InternalId { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Category { get; set; }
        public string Location { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int ReminderMinutesBeforeStart { get; set; }
        public bool Notification { get; set; }
        public bool IsPrivate { get; set; }
        public byte Priority { get; set; }
        public int AppointmentId { get; set; }
        public int AdapterId { get; set; }
        public Nullable<int> Tag { get; set; }
        public bool Upload { get; set; }
    
        public virtual Adapters Adapters { get; set; }
        public virtual Appointments Appointments { get; set; }
    }
}
