//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Today.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSoldToCustomers
    {
        public int Id { get; set; }
        public System.Guid InternalId { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Category { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime SoldWhen { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Units { get; set; }
        public Nullable<int> ProductUsageId { get; set; }
        public string ProductUsageComment { get; set; }
        public Nullable<decimal> ProductUsageSuccessLevel { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
        public virtual ProductUsages ProductUsages { get; set; }
    }
}
