// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Sync.Today.OData")]
[assembly: AssemblyProductAttribute("Sync.Today")]
[assembly: AssemblyDescriptionAttribute("Sync.Today is a business processes automation platform. It is an application integration server. Exchanging business documents among different systems both within or across organizational boundaries Sync.Today integrates business processes.")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
