/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [Id]
      ,[InternalId]
      ,[ExternalId]
      ,[Body]
      ,[Start]
      ,[End]
      ,[LastModifiedTime]
      ,[Location]
      ,[IsReminderSet]
      ,[AppointmentState]
      ,[Subject]
      ,[RequiredAttendeesJSON]
      ,[ReminderMinutesBeforeStart]
      ,[Sensitivity]
      ,[RecurrenceJSON]
      ,[ModifiedOccurrencesJSON]
      ,[LastOccurrenceJSON]
      ,[IsRecurring]
      ,[IsCancelled]
      ,[ICalRecurrenceId]
      ,[FirstOccurrenceJSON]
      ,[DeletedOccurrencesJSON]
      ,[AppointmentType]
      ,[Duration]
      ,[StartTimeZone]
      ,[EndTimeZone]
      ,[AllowNewTimeProposal]
      ,[CategoriesJSON]
      ,[ServiceAccountId]
      ,[Upload]
      ,[Tag]
      ,[IsNew]
      ,[WasJustUpdated]
      ,[DownloadRound]
      ,[LastDLError]
      ,[LastUPError]
  FROM [ExchangeAppointments]
  Where IsNew = 0 AND [WasJustUpdated] = 0 and [ServiceAccountId] = @ServiceAccountId
